# Generated by Django 5.1.5 on 2025-01-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_fax_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='entity',
            field=models.CharField(choices=[('Enterprise', 'Enterprise'), ('Individual', 'Individual'), ('Government', 'Government')], db_index=True, default='Individual'),
        ),
    ]
